platform :ios, '7.0'
  
target 'SharedBicycle' do
 pod 'AMap2DMap'
 pod 'AMapSearch'
 pod 'AMapLocation'
 pod 'AFNetworking'
 pod 'CWLateralSlide', '~> 1.5.8'
 pod 'MBProgressHUD'
 pod 'TZImagePickerController'
 pod 'MJRefresh'
end
